services:
  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks:
      - private  
    depends_on:
      - frontend
      - backend
  backend:
    build: ./mern/backend
    networks:
      - private
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongodb
  frontend:
    build: ./mern/frontend
    env_file:
      - ./mern/frontend/.env
    networks:
      - private
  mongodb:
    image: mongo:latest
    networks:
      - private
    volumes:
      - mongo-data:/data/db

networks:
  private:
    driver: bridge

volumes:
  mongo-data:
    driver: local
