services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - private  
  backend:
    build: ./mern/backend
    networks:
      - private
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongodb
  frontend:
    build: ./mern/frontend
    env_file:
      - ./mern/frontend/.env
    networks:
      - private
  mongodb:
    image: mongo:latest
    networks:
      - private
    volumes:
      - mongo-data:/data/db

networks:
  private:
    driver: bridge

volumes:
  mongo-data:
    driver: local
